version: '3'
services:
  node:
    image: node:14
    user: 1000:1000
    working_dir: /opt/app
    #ports:
    #- 5555:5555
    volumes:
    - .:/opt/app
    command: bash -c "npm i && npm run watch"
